
export { default as volcanArenal01 } from '../../assets/images/volcanArenal01.jpg'
export { default as lagoArenal01 } from '../../assets/images/lagoArenal01.jpg'
export { default as rioCeleste01 } from '../../assets/images/IMG-20220313-WA0058.jpg'
export { default as rioCeleste02 } from '../../assets/images/IMG-20220313-WA0058.jpg'
export { default as imageFooter } from '../../assets/images/20220604_091349.jpg'
export { default as safari } from '../../assets/images/safari.jpg'
export { default as rafting1 } from '../../assets/images/rafting1.jpg'
export { default as rafting2 } from '../../assets/images/rafting2.jpg'
export { default as rana } from '../../assets/images/[000072].jpg'
export { default as hikings } from '../../assets/images/hikings.jpg'
export { default as hikings1 } from '../../assets/images/hikings1.jpg'
export { default as hikings2 } from '../../assets/images/hikings2.jpg'
export { default as safariFloatWildLifeArenal } from '../../assets/images/20210624_102736.jpg'
export { default as hangingBridges} from '../../assets/images//20220324_153317.jpg'
export { default as house1} from '../../assets/images/house1.webp'
export { default as house2} from '../../assets/images/house2.webp'
export { default as house3} from '../../assets/images/house3.webp'
export { default as house4} from '../../assets/images/house4.webp'
export { default as house5} from '../../assets/images/house5.webp'
export { default as house6} from '../../assets/images/house6.webp'
export { default as house7} from '../../assets/images/house7.webp'
export { default as house8} from '../../assets/images/house8.webp'
export { default as house9} from '../../assets/images/house9.webp'
export { default as house10} from'../../assets/images/house10.webp'
export { default as tubing1} from'../../assets/images/IMG_1147.jpeg'
export { default as tubing2} from'../../assets/images/IMG_1171.jpeg'
export { default as tubing3} from'../../assets/images/IMG_1456.jpeg'
export { default as tubing4} from'../../assets/images/house10.webp'
