export { default as leftArrow } from '../../assets/icons/left-arrow.svg'
export { default as rightArrow } from '../../assets/icons/right-arrow.svg'
export { default as backpacking } from '../../assets/icons/backpacking-trips.svg'
export { default as trip } from '../../assets/icons/corporate-trips.svg'
export { default as customisedTrip } from '../../assets/icons/customised-trips.svg'
export { default as zipline} from '../../assets/icons/zip-line.png'
export { default as arrowRight} from '../../assets/icons/icons8-forward-button-20.png'
